[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps = 
    adafruit/Adafruit DHT sensor@^3.3.10
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    tzapu/WiFiManager@^2.0.16
    links2004/WebSockets@^2.4.2

build_flags = 
    -DDISCORD_WEBHOOK_URL=\"${this.discord_webhook_url}\"

monitor_speed = 115200